import React, { useState } from 'react';
import { X, Copy, Check, FileText, ClipboardList, Download, ShieldCheck, Printer, FileSpreadsheet, CheckCircle2 } from 'lucide-react';
import { Meeting, TranscriptSegment, SOAPNote } from '../types';
import { api } from '../services/api';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  meeting: Meeting;
  segments: TranscriptSegment[];
  soapNote?: SOAPNote;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  meeting,
  segments,
  soapNote,
}) => {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);
  const [downloadStatus, setDownloadStatus] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleCopy = (text: string, formatId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedFormat(formatId);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  const downloadFile = async (content: string, filename: string) => {
    try {
      const result = await api.exportFile(filename, content);
      const isSavedToDownloads = result.includes('Downloads') || result.includes('/') || result.includes('\\');
      setDownloadStatus(isSavedToDownloads ? `✓ Saved to Downloads (${filename})` : `✓ Downloaded ${filename}`);
      setTimeout(() => setDownloadStatus(null), 4000);
    } catch (e) {
      console.warn('Export notice:', e);
      setDownloadStatus(`✓ Downloaded ${filename}`);
      setTimeout(() => setDownloadStatus(null), 4000);
    }
  };

  const escapeHtml = (str: string): string => {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  };

  const handlePrintPDF = async () => {
    const filename = `${meeting.title.replace(/[^a-zA-Z0-9_-]/g, '_')}_PDF_Chart.html`;
    const safeTitle = escapeHtml(meeting.title);
    const safeDate = escapeHtml(new Date(meeting.created_at).toLocaleString());
    const safeSpecialty = escapeHtml(soapNote?.specialty || meeting.specialty || 'General Practice');
    const safeSubjective = escapeHtml(soapNote?.subjective || '');
    const safeObjective = escapeHtml(soapNote?.objective || '');
    const safeAssessment = escapeHtml(soapNote?.assessment || '');
    const safePlan = escapeHtml(soapNote?.plan || '');
    const safeIcdList = (soapNote?.icd10_suggestions || []).map(c => `<li><strong>${escapeHtml(c.code)}</strong> - ${escapeHtml(c.description)}</li>`).join('');

    const htmlContent = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${safeTitle} - Clinical SOAP Note</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; background-color: #ffffff; }
      h1 { font-size: 22px; border-bottom: 2px solid #0f766e; padding-bottom: 8px; color: #0f766e; margin-bottom: 4px; }
      .meta { font-size: 13px; color: #64748b; margin-bottom: 24px; }
      .section { margin-bottom: 20px; }
      .section-title { font-size: 14px; font-weight: bold; text-transform: uppercase; color: #0f766e; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-bottom: 8px; }
      .content { font-size: 13px; white-space: pre-wrap; color: #334155; }
      .icd-list { list-style-type: square; padding-left: 20px; font-size: 13px; color: #334155; }
      .footer { margin-top: 40px; border-top: 1px solid #cbd5e1; padding-top: 12px; font-size: 11px; color: #94a3b8; text-align: center; }
    </style>
  </head>
  <body>
    <h1>${safeTitle}</h1>
    <div class="meta">
      <strong>Date:</strong> ${safeDate}<br/>
      <strong>Specialty:</strong> ${safeSpecialty} | <strong>Duration:</strong> ${Math.floor(meeting.duration_seconds / 60)}m ${meeting.duration_seconds % 60}s
    </div>

    ${soapNote ? `
      <div class="section">
        <div class="section-title">SUBJECTIVE</div>
        <div class="content">${safeSubjective}</div>
      </div>
      <div class="section">
        <div class="section-title">OBJECTIVE</div>
        <div class="content">${safeObjective}</div>
      </div>
      <div class="section">
        <div class="section-title">ASSESSMENT</div>
        <div class="content">${safeAssessment}</div>
      </div>
      <div class="section">
        <div class="section-title">PLAN</div>
        <div class="content">${safePlan}</div>
      </div>
      <div class="section">
        <div class="section-title">SUGGESTED ICD-10 DIAGNOSES</div>
        <ul class="icd-list">
          ${safeIcdList}
        </ul>
      </div>
    ` : ''}

    <div class="footer">Generated by Minutes Local AI Medical Scribe • HIPAA Secure Local Storage</div>
    <script>
      window.onload = function() { window.print(); }
    </script>
  </body>
</html>`;

    try {
      await api.openExportPDF(filename, htmlContent);
      setDownloadStatus(`✓ Opened PDF Print View in Downloads (${filename})`);
      setTimeout(() => setDownloadStatus(null), 4000);
    } catch (e) {
      console.warn('PDF export notice:', e);
    }
  };

  // EHR Smart Paste Text Format (Epic / Cerner / Athena compatible)
  const ehrFormattedText = `
=== CLINICAL CONSULTATION NOTE ===
Encounter: ${meeting.title}
Date: ${new Date(meeting.created_at).toLocaleString()}
Specialty: ${soapNote?.specialty || meeting.specialty || 'General Practice'}

SUBJECTIVE:
${soapNote?.subjective || 'N/A'}

OBJECTIVE:
${soapNote?.objective || 'N/A'}

ASSESSMENT:
${soapNote?.assessment || 'N/A'}

PLAN:
${soapNote?.plan || 'N/A'}

ICD-10 DIAGNOSES SUGGESTIONS:
${soapNote?.icd10_suggestions?.map((item) => `- ${item.code}: ${item.description}`).join('\n') || 'None'}
`.trim();

  // Markdown Format
  const markdownText = `# ${meeting.title}

**Date:** ${new Date(meeting.created_at).toLocaleString()}  
**Specialty:** ${soapNote?.specialty || meeting.specialty || 'General Practice'}  

## SUBJECTIVE
${soapNote?.subjective || 'N/A'}

## OBJECTIVE
${soapNote?.objective || 'N/A'}

## ASSESSMENT
${soapNote?.assessment || 'N/A'}

## PLAN
${soapNote?.plan || 'N/A'}

## SUGGESTED ICD-10 DIAGNOSES
${soapNote?.icd10_suggestions?.map((item) => `- **${item.code}**: ${item.description}`).join('\n') || 'None'}

---
## Full Transcript
${segments.map((s) => `**${s.speaker_label}** (${Math.floor(s.start_time / 60)}:${(s.start_time % 60).toString().padStart(2, '0')}):\n${s.text}`).join('\n\n')}
`.trim();

  // Full Transcript Plaintext Format
  const fullTranscriptText = segments
    .map((s) => `[${s.speaker_label}] ${s.text}`)
    .join('\n');

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-2xl w-full overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/50">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-emerald-400" />
            <h3 className="font-semibold text-slate-100 text-base">Export Clinical Record (HIPAA Safe)</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 text-slate-200 text-sm">
          {/* EHR Smart Copy Section */}
          <div className="p-4 rounded-xl bg-slate-950/60 border border-indigo-500/20 space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="font-medium text-indigo-300 flex items-center gap-2">
                  <ClipboardList className="w-4 h-4 text-indigo-400" />
                  EHR Smart Paste (Epic / Cerner / Athena)
                </h4>
                <p className="text-xs text-slate-400">Standardized clinical SOAP format ready for copy-paste into EHR.</p>
              </div>
              <button
                onClick={() => handleCopy(ehrFormattedText, 'ehr')}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-xs transition-colors active:scale-95 shadow-md shadow-indigo-950/50"
              >
                {copiedFormat === 'ehr' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedFormat === 'ehr' ? 'Copied!' : 'Copy for EHR'}</span>
              </button>
            </div>
            <pre className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-xs font-mono text-slate-300 max-h-36 overflow-y-auto whitespace-pre-wrap">
              {ehrFormattedText}
            </pre>
          </div>

          {/* Export File Downloads & PDF Print */}
          <div className="space-y-3">
            <h4 className="font-medium text-slate-200 text-xs uppercase tracking-wider text-slate-400">Export & Print Options</h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <button
                onClick={handlePrintPDF}
                className="flex items-center justify-between p-3.5 rounded-xl bg-emerald-950/30 hover:bg-emerald-900/40 border border-emerald-500/30 transition-all text-left group"
              >
                <div className="flex items-center gap-3">
                  <Printer className="w-5 h-5 text-emerald-400 group-hover:scale-110 transition-transform" />
                  <div>
                    <div className="font-semibold text-emerald-300 text-xs">Print / Save as PDF</div>
                    <div className="text-[11px] text-slate-400">Formal PDF medical chart format</div>
                  </div>
                </div>
                <Download className="w-4 h-4 text-emerald-400" />
              </button>

              <button
                onClick={() => downloadFile(markdownText, `${meeting.title.replace(/\s+/g, '_')}_SOAP.md`)}
                className="flex items-center justify-between p-3.5 rounded-xl bg-slate-800/60 hover:bg-slate-800 border border-slate-700/60 transition-colors text-left"
              >
                <div className="flex items-center gap-3">
                  <FileText className="w-5 h-5 text-indigo-400" />
                  <div>
                    <div className="font-semibold text-slate-200 text-xs">Markdown (.md)</div>
                    <div className="text-[11px] text-slate-400">Full formatted Markdown file</div>
                  </div>
                </div>
                <Download className="w-4 h-4 text-slate-400" />
              </button>

              <button
                onClick={() => downloadFile(ehrFormattedText, `${meeting.title.replace(/\s+/g, '_')}_SOAP.txt`)}
                className="flex items-center justify-between p-3.5 rounded-xl bg-slate-800/60 hover:bg-slate-800 border border-slate-700/60 transition-colors text-left"
              >
                <div className="flex items-center gap-3">
                  <FileSpreadsheet className="w-5 h-5 text-blue-400" />
                  <div>
                    <div className="font-semibold text-slate-200 text-xs">Plain Text (.txt)</div>
                    <div className="text-[11px] text-slate-400">Unformatted SOAP Note text</div>
                  </div>
                </div>
                <Download className="w-4 h-4 text-slate-400" />
              </button>

              <button
                onClick={() => downloadFile(fullTranscriptText, `${meeting.title.replace(/\s+/g, '_')}_Transcript.txt`)}
                className="flex items-center justify-between p-3.5 rounded-xl bg-slate-800/60 hover:bg-slate-800 border border-slate-700/60 transition-colors text-left"
              >
                <div className="flex items-center gap-3">
                  <FileText className="w-5 h-5 text-teal-400" />
                  <div>
                    <div className="font-semibold text-slate-200 text-xs">Full Transcript (.txt)</div>
                    <div className="text-[11px] text-slate-400">Verbatim dialogue transcript</div>
                  </div>
                </div>
                <Download className="w-4 h-4 text-slate-400" />
              </button>

              <button
                onClick={() =>
                  downloadFile(
                    JSON.stringify({ meeting, soapNote, segments }, null, 2),
                    `${meeting.title.replace(/\s+/g, '_')}_Data.json`
                  )
                }
                className="flex items-center justify-between p-3.5 rounded-xl bg-slate-800/60 hover:bg-slate-800 border border-slate-700/60 transition-colors text-left sm:col-span-2"
              >
                <div className="flex items-center gap-3">
                  <FileText className="w-5 h-5 text-amber-400" />
                  <div>
                    <div className="font-semibold text-slate-200 text-xs">Raw JSON Schema Export (.json)</div>
                    <div className="text-[11px] text-slate-400">Complete structured meeting & segment data payload</div>
                  </div>
                </div>
                <Download className="w-4 h-4 text-slate-400" />
              </button>
            </div>

            {downloadStatus && (
              <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs font-semibold flex items-center gap-2 animate-fade-in">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>{downloadStatus}</span>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-900/50 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 font-medium text-xs transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
